### PR TITLE
Adds support for custom plugin registrant

### PR DESCRIPTION
**Pull request by cmaster11**
Adds support for custom plugin registrant, so that FlutterIsolatePlugin can register also custom method channels and other non-automatically-generated plugins.

### CODE REVIEW

**Comment by addie9000** [comment]
This PR helps us to solve the problem with Google Sign In Plugin.
It crashes if isolated plugin uses GeneratedPluginRegistrant.

Ref: https://github.com/flutter/flutter/issues/44564#issuecomment-580198071

**Comment by ryanheise** [comment]
Hi @cmaster11 , do you feel this PR is currently stable to merge into the latest version?

I don't have a use case or test case for this feature, so I'll have to rely on your own testing.

**Comment by agent3bood** [comment]
This PR helped me this issue https://github.com/rmawatson/flutter_isolate/issues/50

I was able to register the plugins that I need to be used inside the isolate without using `GeneratedPluginRegistrant`

**Comment by nmfisher** [comment]
@cmaster11 I've just taken over this package as maintainer, is this PR still required given the latest versions of Flutter/google_sign_in etc?

**Comment by cmaster11** [comment]
@nmfisher some time has passed since I created this PR, but it was definitely NOT related only to Google sign in.

It helped in the generic case where you need to register other methods/channels to be used by Flutter.

**Comment by agent3bood** [comment]
@cmaster11 Merging this PR (or allowing similar feature) will help in solving many issues. 
I am using this PR to solve issues with the following packages `flutter_facebook_login ` and `google_sign_in `.

My use case is:
My app register `flutter_facebook_login ` and `google_sign_in ` for the main Flutter app. But when I use this package it will register the same plugins again for the isolate which will crash the app. The solution is NOT to register the plugins again.

**Comment by cmaster11** [comment]
@nmfisher I've merged the latest master, so the PR should be now ready to be merged

**Comment by nmfisher** [comment]
@cmaster11 You must be psychic, I've literally been looking at this for the past hour.

**Comment by nmfisher** [comment]
Bumping for @cmaster11 - if no response within the next 7 days I will merge this in.

**Comment by cmaster11** [comment]
@nmfisher, the PR looks absolutely good with the new changes :) Please go ahead with the merging!

**Pull request merged**
