### PR TITLE
* update android AGP 7.4.2 / compile sdk 34

### PR DESCRIPTION
**Pull request by angcyo**
* fix `error: resource android:attr/lStar not found.`

```
Execution failed for task ':flutter_isolate:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/angcyo/project/Flutter/BeebLaser/build/flutter_isolate/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

### CODE REVIEW

**Comment by CaptainDario** [comment]
@nmfisher thank you!
This is preventing me from building my app with flutter 3.24

**Comment by nmfisher** [comment]
Thanks @angcyo. 

Should be available as `2.1.0-pre` shortly.

https://pub.dev/packages/flutter_isolate/versions/2.1.0-pre

**Comment by chotixity** [comment]
Having the same error, could you release it to the stable version?

**Comment by nmfisher** [comment]
> Having the same error, could you release it to the stable version?

Available as 2.1.0 now on pub.dev

**Pull request merged**
