### PR TITLE
v2 embedding implemented

### PR DESCRIPTION
**Pull request by rohansohonee**
@ryanheise @rmawatson 
I have implemented v2 embedding and have also kept backwards compatibility with v1.

### CODE REVIEW

**Comment by ryanheise** [comment]
Cool. By the way, it could be a good idea to update the .gitignore to exclude your IDE's config files and the flutter_export_environment.sh file (which accidentally I included in my last PR).

**Comment by ryanheise** [comment]
Your IDE files are still included since the .gitignore will only protect against future git adds, so maybe you need this extra step:

https://stackoverflow.com/questions/13541615/how-to-remove-files-that-are-listed-in-the-gitignore-but-still-on-the-repositor

**Comment by rohansohonee** [comment]
I ran the command but it has only deleted ``flutter_isolate.iml``
I have used the default gitignore file that flutter provides.
How do i remove the other files??

**Comment by rmawatson** [comment]
```
            if (activeIsolates.get(isolateId).engine == null)
                activeIsolates.get(isolateId).view.destroy();
            activeIsolates.get(isolateId).engine.destroy(); 
```

Not really using flutter so I haven't tested anything. This looks wrong. Surely else is required.

**Comment by rohansohonee** [comment]
My bad. I missed the else.

**Comment by ryanheise** [comment]
I don't have a v1 project on hand to test (and the example doesn't compile), but the confirmation in #41 that it works must have been from a v2 user since it was tested before the else was added.

Backward compatibility with v1 hasn't been confirmed by anyone else, but I'm happy to just go ahead and publish this because most people are on v2 now (or else "should" be), and people who are now using Flutter post 1.12 simply cannot use this plugin until this PR gets published.

Note that there is also a long standing open issue on flutter/flutter which may make this plugin unnecessary: https://github.com/flutter/flutter/issues/13937 so probably best to be practical at this stage.

**Comment by rohansohonee** [comment]
@ryanheise 
> Note that there is also a long standing open issue on flutter/flutter which may make this plugin unnecessary: flutter/flutter#13937 so probably best to be practical at this stage.

Do you mean the FlutterIsolate plugin is unnecessary? or supporting v1??

**Comment by ryanheise** [comment]
If they did fix https://github.com/flutter/flutter/issues/13937 then yes it would make this plugin redundant, but I only mention that to put things in perspective because there are a lot of things we could do to improve the project (create test cases, create two versions of the example activity, one for v1 and one for v2, start using a change log and semantic versioning to reflect those changes, etc. etc.) but I think the main thing is, as long as v2 works, that's probably more important than everything else. Even if v1 hasn't been tested or confirmed, it's no biggy, since people looking for this plugin are really just looking for a workaround for that linked issue above, and as long as it works after they update their projects to v2 (as they should), they should be satisfied.

I'm just looking at releasing this now. It's recommending me to make some changes to pubspec which I'm now doing.

**Comment by ryanheise** [comment]
(One possible improvement that might be worth doing is to fix the example so it actually compiles - but I also haven't done it for the same practicality reasons as above. If someone else were to submit a PR, that would be nice :-) )

**Comment by ryanheise** [comment]
OK, this is now published.

**Pull request merged**
